server:
  port: 8016
spring:
      servlet:
       multipart:
         max-file-size: 102400000
      datasource:
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://47.107.86.141:3306/godsell?useUnicode=true&amp;characterEncoding=UTF-8
        username: root
        password: 123456
        type: com.alibaba.druid.pool.DruidDataSource
        dbcp2:                                          # 进行数据库连接池的配置
              min-idle: 5                                   # 数据库连接池的最小维持连接数
              initial-size: 5                               # 初始化提供的连接数
              max-total: 5                                  # 最大的连接数
              max-wait-millis: 200                          # 等待连接获取的最大超时时间

      mvc:
        static-path-pattern: /**
        resources:
          static-locations: classpath:/static/

mybatis-plus:
    mapper-locations: classpath:mapper/**/*.xml
    #实体扫描，多个package用逗号或者分号分隔
    typeAliasesPackage: com.sellgod.propaganda.entity
    global-config:
      #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
      id-type: 0
      #字段策略 0:"忽略判断",1:"非 NULL 判断"),2:"非空判断"
      field-strategy: 2
      #驼峰下划线转换
      db-column-underline: true
      #刷新mapper 调试神器
      refresh-mapper: true
      #数据库大写下划线转换
      #capital-mode: true
      #序列接口实现类配置
      #key-generator: com.baomidou.springboot.xxx
      #逻辑删除配置
      logic-delete-value: -1
      logic-not-delete-value: 0
      #自定义填充策略接口实现
      #meta-object-handler: com.baomidou.springboot.xxx
      #自定义SQL注入器
      sql-injector: com.baomidou.mybatisplus.mapper.LogicSqlInjector

    configuration:
      map-underscore-to-camel-case: true
      cache-enabled: false
      call-setters-on-nulls: true
      local-cache-scope: statement

#logging
logging:
  level:
     com.hnzhzw.test.dao: debug


land:
   jwt:
        # 加密秘钥
          secret: f4e2e52034348f86b67cde581c0f9eb5[shareschain]
            # token有效时长，7天，单位秒
          #expire: 604800
          expire: 604800
          header: token

qiniu:
   AK: teJa9qnHMTWeKBW6bSrwsQZFS7b42aW5vGJD0I32
   SK: myC3egSPOAm9jkhmIXtcKl91pIfn5if-FeBZUIcZ
   bucketname: gold
   URL: http://puqbaf6ym.bkt.clouddn.com

app:
  wx:
   appid: wxfa81b06bca854196
   secret: 5434138a76f914e6896450d4b35706e0














